### ISSUE TITLE
Message for strings validations

### ISSUE THREAD

**Issue by bigotto** [vini-barba/class-validator-translator#13]
- Contains
- NotContains
- IsAlpha
- IsAlphanumeric
- IsDecimal
- IsAscii
- IsBase64
- IsByteLength
- IsCreditCard
- IsCurrency
- IsEmail
- IsFQDN
- IsFullWidth
- IsHalfWidth
- IsVariableWidth
- IsHexColor
- IsHexadecimal
- IsMacAddress
- IsIP
- IsPort
- IsISBN
- IsISIN
- IsISO8601
- IsJSON
- IsJWT
- IsLowercase
- IsMobilePhone
- IsISO31661Alpha2
- IsISO31661Alpha3
- IsMongoId
- IsMultibyte
- IsSurrogatePair
- IsUrl
- IsUUID
- IsFirebasePushId
- IsUppercase
- Length
- MaxLength
- MinLength
- Matches
- IsPhoneNumber
- IsMilitaryTime
- IsHash
- IsISSN
- IsDateString
- IsBooleanString
- IsNumberString
- IsBase32
- IsBIC
- IsBtcAddress
- IsDataURI
- IsEAN
- IsEthereumAddress
- IsHSL
- IsIBAN
- IsIdentityCard
- IsISRC
- IsLocale
- IsMagnetURI
- IsMimeType
- IsOctal
- IsPassportNumber
- IsPostalCode
- IsRFC3339
- IsRgbColor
- IsSemVer

**Comment by bigotto** [comment]
-  Contains
-  NotContains
-  IsAlpha
-  IsAlphanumeric
-  IsDecimal
-  IsAscii
-  IsBase64
-  IsByteLength
-  IsCreditCard
-  IsCurrency
-  IsEmail
-  IsFQDN
-  IsFullWidth
-  IsHalfWidth
-  IsVariableWidth
-  IsHexColor
-  IsHexadecimal
-  IsMacAddress
-  IsIP
-  IsPort
-  IsISBN
-  IsISIN
-  IsISO8601
-  IsJSON
-  IsJWT
-  IsLowercase
-  IsMobilePhone
-  IsISO31661Alpha2
-  IsISO31661Alpha3
-  IsMongoId
-  IsMultibyte
-  IsSurrogatePair
-  IsUrl
-  IsUUID
-  IsFirebasePushId
-  IsUppercase
-  Length
-  MaxLength
-  MinLength
-  Matches
-  IsPhoneNumber
-  IsMilitaryTime
-  IsHash
-  IsISSN
-  IsDateString
-  IsBooleanString
-  IsNumberString
-  IsBase32
-  IsBIC
-  IsBtcAddress
-  IsDataURI
-  IsEAN
-  IsEthereumAddress
-  IsHSL
-  IsIBAN
-  IsIdentityCard
-  IsISRC
-  IsLocale
-  IsMagnetURI
-  IsMimeType
-  IsOctal
-  IsPassportNumber
-  IsPostalCode
-  IsRFC3339
-  IsRgbColor
-  IsSemVer

**Comment by vini-barba** [comment]
@bigotto i've created an issue for each item, so i'm going to archive this issue, since it's not necessary anymore

**Comment by vini-barba** [comment]
@bigotto  i've created an issue for each item, so i'm going to archive this issue, since it's not necessary anymore
